import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import Navbar from './components/Navbar'
import Head from 'next/head'

const poppins = Poppins({
    weight: ['300', '400', '500', '600', '700'],
    subsets: ['latin']
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={`${poppins.className} bg-primary text-white mx-5 flex justify-center`}>
                <div className='max-w-7xl w-full'>
                    <Navbar />
                    {children}
                </div>
            </body>
        </html>
    )
}
